import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/sheared/NavBar";
import Footer from "@/components/sheared/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="dark"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning /* <--- এখানে যোগ করুন */
    >
      <body 
        className="min-h-full flex flex-col"
        suppressHydrationWarning /* <--- এখানেও যোগ করুন */
      >
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}